import Head from "next/head";
import styles from "../styles/Home.module.css";
import { CountdownCircleTimer } from "react-countdown-circle-timer";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to CC timer Demo
        </h1>
        <br />
        <br />

        <CountdownCircleTimer
          isPlaying
          // 👇 カウントダウンする秒数
          duration={5}
          // 👇 カウントダウンサークルの色と保持する時間の割合
          colors={[
            ["#004777", 0.33],
            ["#F7B801", 0.33],
            ["#A30000", 0.33],
          ]}
        >
          {({ remainingTime }) => remainingTime}
        </CountdownCircleTimer>
      </main>

      <footer className={styles.footer}>
      <a href="./option">And more</a>
      </footer>
    </div>
  );
};
export default Home;
